PROPERTIES_VIEW = [
    "Contact owner",
    "First Name",
    "Last Name",
    "Email",
    "Phone Number",
    "Promo",
    "Alumni",
    "Job Title",
    "Expertise",
    "City",
    "State/Region",
    "Country",
    "Membership Notes",
    "Employment status",
    "Shasta Mentor",
    "Shasta Intern",
    "Shasta Grant",
    "Shasta Employer",
    "Donation",
    "Company Name",
    "Company Size",
    "Email Domain",
    "Industry"
]